### ISSUE TITLE
为什么我放入了根文件的lib里面 ，新建了 example 文件夹，然后放里面，又在插件的example也放了，都没有效果。

### ISSUE THREAD

**Issue by BZBY** [yhArcadia/TTS-for-Yunzai-Bot#1]

**Comment by yhArcadia** [comment]
报错“请确认你的ffmpeg可以处理此转换”的话，需要安装ffmpeg。
另外这个是V2云崽版，不支持V3，V3的我回头传一下。

**Comment by yhArcadia** [comment]
https://github.com/yhArcadia/TTS-for-Yunzai-Bot/blob/dff1f23d32e9e8c4b5bd99f14f85a356155ce2eb/%E5%8E%9F%E7%A5%9E%E8%A7%92%E8%89%B2%E8%AF%AD%E9%9F%B3%E5%90%88%E6%88%90(V3).js

**Comment by daigexiaodongdong** [comment]
![image](https://user-images.githubusercontent.com/50607528/187440212-35690a13-5118-43fc-bbb9-13f57ff5afb2.png)
大佬，v3报错，明明ffmpeg也装了
